"""

This software reads a list of TXT files generated by XXXX software
and plot the Elevation Maps and Intersections of the segments in
the respective PNG file.

"""

from TrackReader import TrackFileReader, Track
from TrackViewer import TrackViewer, TrackPlotInfo
from pathlib import Path
import sys


def Plotear(fileName):
    
    reader = TrackFileReader()
    reader.ReadFile(fileName)
    track = reader.GetTrack()

    imageName = fileName[:-3] + "png"

    title = Path(fileName).stem

    pInfo = TrackPlotInfo(track, title)
    pInfo.ExtractTrackData()

    viewer = TrackViewer()    
    plot1 = viewer.BuildPlot(pInfo, intersection_window=40)
    viewer.SavePlotAs(plot1, imageName)


def main():
        
    if len(sys.argv) == 1:
        print("Use with list of txt file to parse: E.g.: python plottxt.py file1.txt file2.txt file3.txt")

    fileToParse = sys.argv[1:]

    finalList = CheckFileList(fileToParse)
    
    for f in finalList:
        print ("Plotting file '", f, "' ...........", end= " ")
        Plotear(f)
        print ("Done!")

    


def CheckFileList(fileToParse):
    finalList = list(fileToParse)

    for f in fileToParse:
        file = Path(f)
        if not file.exists():
            print ("File ", f, "not found or is not a file. Removed from list")
            finalList.remove(f)

    print ('\nFiles to plot:', finalList)

    return finalList

if __name__ == "__main__":
    main()